"""Initial migration.

Revision ID: 740dae66fb95
Revises: 
Create Date: 2024-05-30 00:04:33.839349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740dae66fb95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish', sa.String(length=100), nullable=False),
    sa.Column('beverage', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    # ### end Alembic commands ###
